packages/secretlint/test/snapshots/--format=json/output.txt
packages/secretlint/test/snapshots/basic/output.txt
packages/secretlint/test/snapshots/secretlintignore/output.txt

`npm test`すると失敗するテストがあったので見てみたのですが、もしかすると期待値の方がアップデートされていないのかも知れない思い、PRを作ってみました。勘違いであったらスミマセン。

update expected values to pass tests

---

packages/@secretlint/secretlint-rule-aws/src/index.ts
packages/@secretlint/secretlint-rule-aws/test/index.test.ts
packages/@secretlint/secretlint-rule-aws/test/snapshots/AWS Secret Access Key/output.json
packages/@secretlint/tester/src/index.ts

fix(aws): report only found Access key

---

README.md
packages/@secretlint/secretlint-rule-basicauth/LICENSE
packages/@secretlint/secretlint-rule-basicauth/README.md
packages/@secretlint/secretlint-rule-basicauth/package.json
packages/@secretlint/secretlint-rule-basicauth/src/index.ts
packages/@secretlint/secretlint-rule-basicauth/test/index.test.ts
packages/@secretlint/secretlint-rule-basicauth/test/mocha.opts
packages/@secretlint/secretlint-rule-basicauth/test/snapshots/ng.basic-auth-ftp-url/input.txt
packages/@secretlint/secretlint-rule-basicauth/test/snapshots/ng.basic-auth-ftp-url/output.json
packages/@secretlint/secretlint-rule-basicauth/test/snapshots/ng.basic-auth-http-url/input.txt
packages/@secretlint/secretlint-rule-basicauth/test/snapshots/ng.basic-auth-http-url/output.json
packages/@secretlint/secretlint-rule-basicauth/test/snapshots/ok.valid-url/input.txt
packages/@secretlint/secretlint-rule-basicauth/test/snapshots/ok.valid-url/output.json
packages/@secretlint/secretlint-rule-basicauth/test/tsconfig.json
packages/@secretlint/secretlint-rule-basicauth/tsconfig.json
packages/@secretlint/secretlint-rule-preset-recommend/README.md
packages/@secretlint/secretlint-rule-preset-recommend/package.json
packages/@secretlint/secretlint-rule-preset-recommend/src/index.ts
packages/@secretlint/secretlint-rule-preset-recommend/test/snapshots/basicauth/input
packages/@secretlint/secretlint-rule-preset-recommend/test/snapshots/basicauth/output.json
packages/@secretlint/tester/src/index.ts

feat(basicauth): add @secretlint/secretlint-rule-basicauth

---

packages/@secretlint/secretlint-rule-aws/README.md
packages/@secretlint/secretlint-rule-basicauth/README.md
packages/@secretlint/secretlint-rule-npm/README.md
packages/@secretlint/secretlint-rule-preset-recommend/README.md
packages/@secretlint/secretlint-rule-privatekey/README.md
packages/@secretlint/secretlint-rule-slack/README.md
packages/@secretlint/secretlint-scripts/configs/README.md.template

docs(packages): change "Rules" to "Messages"

---

packages/@secretlint/core/src/RuleContext.ts
packages/@secretlint/core/src/index.ts
packages/@secretlint/core/src/messages/MessageProcessManager.ts
packages/@secretlint/core/src/messages/filter-duplicated-process.ts
packages/@secretlint/core/src/messages/filter-ignored-process.ts
packages/@secretlint/core/src/messages/index.ts
packages/@secretlint/core/src/messages/sort-messages-process.ts
packages/@secretlint/core/test/messages/create-messages-utils.ts
packages/@secretlint/core/test/messages/filter-duplicated-process.test.ts
packages/@secretlint/core/test/messages/filter-ignored-process.test.ts
packages/@secretlint/core/test/messages/sort-messages-process.test.ts
packages/@secretlint/types/src/SecretLintCore.ts
packages/@secretlint/types/src/SecretLintRule.ts
packages/@secretlint/types/src/index.ts

- filter ignored range
- filter duplicated messages
- sort messages by range
fix #3

feat(core): support Context#ignore method

---

packages/@secretlint/node/src/index.ts
packages/secretlint/src/cli.ts

feat(cli): add --debug flag

---

README.md

fix https://github.com/secretlint/secretlint/issues/73

docs: Add git hook globally

---

examples/benchmark/package.json
packages/@secretlint/secretlint-rule-preset-recommend/README.md
packages/@secretlint/secretlint-rule-preset-recommend/package.json
packages/@secretlint/secretlint-rule-preset-recommend/rollup.config.js
packages/@secretlint/secretlint-rule-preset-recommend/test/tsconfig.json
packages/@secretlint/secretlint-rule-preset-recommend/tsconfig.json
yarn.lock

Rollup and distribute bundled file
#8

perf(secretlint-rule-preset-recommend): rollup

---

.secretlintrc.json
docs/credentials-is-secret.md

docs: credentials is secret

---

package.json
packages/@secretlint/config-creator/package.json
packages/@secretlint/config-loader/package.json
packages/@secretlint/config-validator/package.json
packages/@secretlint/core/package.json
packages/@secretlint/core/src/messages/filter-duplicated-process.ts
packages/@secretlint/formatter/package.json
packages/@secretlint/messages-to-markdown/package.json
packages/@secretlint/node/package.json
packages/@secretlint/profiler/package.json
packages/@secretlint/profiler/src/index.ts
packages/@secretlint/quick-start/package.json
packages/@secretlint/secretlint-rule-aws/package.json
packages/@secretlint/secretlint-rule-basicauth/package.json
packages/@secretlint/secretlint-rule-example/package.json
packages/@secretlint/secretlint-rule-gcp/package.json
packages/@secretlint/secretlint-rule-npm/package.json
packages/@secretlint/secretlint-rule-preset-canary/package.json
packages/@secretlint/secretlint-rule-preset-recommend/package.json
packages/@secretlint/secretlint-rule-preset-recommend/rollup.config.js
packages/@secretlint/secretlint-rule-privatekey/package.json
packages/@secretlint/secretlint-rule-slack/package.json
packages/@secretlint/source-creator/package.json
packages/@secretlint/tester/package.json
packages/@secretlint/types/package.json
packages/secretlint/package.json
yarn.lock

chore(deps): update dependencies

---

packages/@secretlint/tester/src/index.ts

fix(tester): sort object be property name

---

publish/docker/Dockerfile

fix(docker): fix invalid label key

---

packages/@secretlint/secretlint-rule-github/.mocharc.json
packages/@secretlint/secretlint-rule-github/LICENSE
packages/@secretlint/secretlint-rule-github/README.md
packages/@secretlint/secretlint-rule-github/package.json
packages/@secretlint/secretlint-rule-github/src/index.ts
packages/@secretlint/secretlint-rule-github/test/index.test.ts
packages/@secretlint/secretlint-rule-github/test/snapshots/ng.apikey/input.txt
packages/@secretlint/secretlint-rule-github/test/snapshots/ng.apikey/output.json
packages/@secretlint/secretlint-rule-github/test/snapshots/ok.valid/input.txt
packages/@secretlint/secretlint-rule-github/test/snapshots/ok.valid/output.json
packages/@secretlint/secretlint-rule-github/test/tsconfig.json
packages/@secretlint/secretlint-rule-github/tsconfig.json
packages/@secretlint/secretlint-rule-no-dotenv/package.json

support new GitHub Token format
fix #153

feat: implement @secretlint/secretlint-rule-github

---

packages/@secretlint/secretlint-rule-gcp/src/index.ts

Fixed typo from CP to GCP

---

CHANGELOG.md
examples/benchmark/CHANGELOG.md
examples/benchmark/package.json
examples/cli/CHANGELOG.md
examples/cli/package.json
lerna.json
packages/@secretlint/formatter/CHANGELOG.md
packages/@secretlint/formatter/package.json
packages/@secretlint/node/CHANGELOG.md
packages/@secretlint/node/package.json
packages/@secretlint/quick-start/CHANGELOG.md
packages/@secretlint/quick-start/package.json
packages/secretlint/CHANGELOG.md
packages/secretlint/package.json

* **formatter:** add "native" table formatter ([#169](https://github.com/secretlint/secretlint/issues/169)) ([6bd7910](https://github.com/secretlint/secretlint/commit/6bd79101458677a08a69bdfc36c0782e3fb90799)) by @susam-projects
You can use `--format table`.
```
$ secretlint --format table "**/*"
```

chore(release): v3.2.0

---

README.md

We have released secretlint as web extension and add it to README 🎉 
- [secretlint/webextension: Detect secrets in your request/response using secretlint.](https://github.com/secretlint/webextension)
It will help you to found secrets in real website.

docs: add secretlint webextension

---

README.md
docs/configuration.md
packages/@secretlint/secretlint-rule-filter-comments/package.json
packages/@secretlint/secretlint-rule-preset-canary/package.json
packages/@secretlint/secretlint-rule-preset-canary/src/index.ts
packages/@secretlint/secretlint-rule-preset-canary/test/snapshots/filter-comments/input.txt
packages/@secretlint/secretlint-rule-preset-canary/test/snapshots/filter-comments/output.json
packages/@secretlint/secretlint-rule-preset-recommend/README.md
packages/@secretlint/secretlint-rule-preset-recommend/package.json
packages/@secretlint/secretlint-rule-preset-recommend/src/index.ts
packages/@secretlint/secretlint-rule-preset-recommend/test/snapshots/filter-comments/input.txt
packages/@secretlint/secretlint-rule-preset-recommend/test/snapshots/filter-comments/output.json

add [@secreting/secretlint-rule-filter-comments](https://www.npmjs.com/package/@secretlint/secretlint-rule-filter-comments) to [@secretlint/secretlint-rule-preset-recommend](https://www.npmjs.com/package/@secretlint/secretlint-rule-preset-recommend)

feat(preset): add @secretlint/secretlint-rule-filter-comments to presets

---

package.json
turbo.json
yarn.lock

chore(deps): update turbo

---

examples/cli/package.json
packages/@secretlint/config-loader/test/index.test.ts
packages/@secretlint/config-loader/test/snapshots/ng.rule-id-missing/output.txt
packages/@secretlint/config-loader/test/snapshots/ng.rule-preset--rule-id/output.txt
yarn.lock

Update to https://github.com/azu/expected-exit-status/releases/tag/v2.0.0

chore(deps): use expected-exit-status@2

---

packages/@secretlint/secretlint-rule-filter-comments/package.json
yarn.lock

fix(secretlint-rule-filter-comments): remove unnecessary deps

---

docs/secretlint-rule.md
packages/@secretlint/config-loader/test/fixtures/valid-config-esm/modules/example/index.mjs
packages/@secretlint/core/test/fixtures/secretlint-rule-example.ts
packages/@secretlint/secretlint-rule-example/src/index.ts
packages/@secretlint/secretlint-rule-internal-test-pure-deps/src/index.ts
packages/@secretlint/secretlint-rule-secp256k1-privatekey/src/index.ts
packages/@secretlint/tester/test/fixtures/secretlint-rule-example.ts

fix(RegExp.exec): refactor while loop + RegExp.exec → matchAll

---

.github/workflows/benchmark.yml
.github/workflows/comment-publish-artifact.yml
.github/workflows/publish.yml

Use GitHub Apps token.
fix #179 
Note: Private key SHA256:4RY

CI: use GitHub Apps instead of PAT

---

.github/workflows/publish.yml

CI(publish): do not run PR is closed without merge

---

publish/docker/Dockerfile

feat(docker): install sarif formatter to docker image

---

packages/@secretlint/quick-start/package.json
packages/@secretlint/secretlint-rule-preset-canary/package.json
packages/@secretlint/secretlint-rule-preset-recommend/package.json
yarn.lock

chore(deps): udpate devDeps

---

README.md

https://secretlint.github.io/ is quick demo site.

docs: add https://secretlint.github.io/

---

docs/secretlint-rule.md

BREAKING CHANGE: you may need to update snapshots via @secretlint/tester
- command line user: No effect
- rule creator: Need to update snapshot
Introduced in #359

docs: add "sourceContent" and "sourceContentType" to message

---

packages/secretlint/README.md

BREAKING CHANGE: It is just update for rule creator

fix!: Update README

---

.github/workflows/benchmark.yml
.github/workflows/publish-artifact.yml
.github/workflows/publish.yml
.github/workflows/test.yml
README.md
examples/benchmark/targets/js-primer/.travis/calibre-3-installer.sh

secretlint no longer tests on Node.js 14.

CI: drop Node.js 14

---

publish/docker/Dockerfile

feat(Dockerfile): install secretlint-rule-pattern

---

publish/docker/README.md

docs(docker): add built-in packages

---

.github/workflows/publish.yml

CI: ::set-output is drepecated

---

CONTRIBUTING.md

Use GitHub Actions to publish new versions

docs: Update Release Flow

---

packages/@secretlint/core/package.json
packages/@secretlint/core/src/RuleContext.ts
packages/@secretlint/core/src/SecretLintSourceCodeImpl.ts
packages/@secretlint/core/src/helper/invariant.ts
packages/@secretlint/core/src/helper/promise-event-emitter.ts
packages/@secretlint/core/src/index.ts
yarn.lock

It does not exists in browser.

refactor(core): remove "events" and "assert" from core

---

lerna.json

fix: remove useWorkspaces option

---

.yarnrc
publish/docker/Dockerfile

 feat(docker): use Node.js 18 as base image 

---

docs/secretlint-rule.md
packages/@secretlint/core/test/fixtures/secretlint-rule-example.ts
packages/@secretlint/messages-to-markdown/test/example-rule.ts
packages/@secretlint/secretlint-rule-aws/test/index.test.ts
packages/@secretlint/secretlint-rule-azure/test/index.test.ts
packages/@secretlint/secretlint-rule-basicauth/test/index.test.ts
packages/@secretlint/secretlint-rule-example/src/index.ts
packages/@secretlint/secretlint-rule-example/test/index.test.ts
packages/@secretlint/secretlint-rule-filter-comments/src/index.ts
packages/@secretlint/secretlint-rule-filter-comments/test/index.test.ts
packages/@secretlint/secretlint-rule-gcp/test/index.test.ts
packages/@secretlint/secretlint-rule-github/test/index.test.ts
packages/@secretlint/secretlint-rule-internal-test-cjs/src/index.ts
packages/@secretlint/secretlint-rule-internal-test-esm/src/index.ts
packages/@secretlint/secretlint-rule-no-dotenv/src/index.ts
packages/@secretlint/secretlint-rule-no-dotenv/test/index.test.ts
packages/@secretlint/secretlint-rule-no-homedir/test/index.test.ts
packages/@secretlint/secretlint-rule-no-k8s-kind-secret/test/index.test.ts
packages/@secretlint/secretlint-rule-npm/test/index.test.ts
packages/@secretlint/secretlint-rule-pattern/test/index.test.ts
packages/@secretlint/secretlint-rule-preset-canary/test/index.test.ts
packages/@secretlint/secretlint-rule-privatekey/test/index.test.ts
packages/@secretlint/secretlint-rule-secp256k1-privatekey/src/index.ts
packages/@secretlint/secretlint-rule-secp256k1-privatekey/test/index.test.ts
packages/@secretlint/secretlint-rule-sendgrid/test/index.test.ts
packages/@secretlint/secretlint-rule-shopify/test/index.test.ts
packages/@secretlint/secretlint-rule-slack/test/index.test.ts
packages/@secretlint/tester/src/index.ts
packages/@secretlint/tester/test/fixtures/secretlint-rule-example.ts
packages/@secretlint/tester/test/index.test.ts

docs: Update rule document

---

.mocharc.json
packages/@secretlint/core/package.json
packages/@secretlint/core/src/SecretLintSourceCodeImpl.ts
yarn.lock

update https://github.com/textlint/structured-source/releases/tag/v4.0.0

fix(core): update structured-source@4

---

packages/@secretlint/core/src/index.ts
packages/@secretlint/secretlint-rule-no-homedir/package.json

fix(no-homedir): add @textlint/regexp-string-matcher as deps

---

packages/@secretlint/secretlint-rule-gcp/src/index.ts
packages/@secretlint/secretlint-rule-npm/src/index.ts

fix: fix weak regex pattern

---

packages/@secretlint/quick-start/package.json

fix https://github.com/secretlint/secretlint/issues/554

fix(quick-start): add the config directory to the install file list

---

examples/cli/package.json
yarn.lock

update https://github.com/azu/expected-exit-status/releases/tag/v3.0.0 and add tests for CLI

test: add stdout test

---

packages/@secretlint/profiler/package.json

fix(profiler): correct browser reference

---

packages/@secretlint/secretlint-rule-gcp/src/index.ts
packages/@secretlint/secretlint-rule-gcp/src/reportIfFoundPrivateKeyP12Format.ts

- browser can not load node:fs
- node-forge is heavy module
It helps you to build secretlint for broser.

fix(gcp): make reportIfFoundPrivateKeyP12Format lazy load

---

.scaffdog/config.js
.scaffdog/new-rule.md
.scaffdog/new-rule/LICENSE
.scaffdog/new-rule/README.md
.scaffdog/new-rule/package.json
.scaffdog/new-rule/src/index.ts
.scaffdog/new-rule/test/index.test.ts
.scaffdog/new-rule/test/snapshots/ng.secret/input.txt
.scaffdog/new-rule/test/snapshots/ng.secret/output.json
.scaffdog/new-rule/test/snapshots/ok.valid/input.txt
.scaffdog/new-rule/test/snapshots/ok.valid/output.json
.scaffdog/new-rule/tsconfig.json
CONTRIBUTING.md
README.md
package.json
yarn.lock

You can use `npm run gen:rule` command to create new rule.
```shell script
npm run gen:rule
```
For more details, please see [CONTRIBUTING.md](./CONTRIBUTING.md)

meta: add `npm run gen:rule` for creating new rule

---

.scaffdog/new-rule.md

fix(scaffdog): add `tsconfig.json`

---

packages/@secretlint/secretlint-rule-openai/LICENSE
packages/@secretlint/secretlint-rule-openai/README.md
packages/@secretlint/secretlint-rule-openai/package.json
packages/@secretlint/secretlint-rule-openai/src/index.ts
packages/@secretlint/secretlint-rule-openai/test/index.test.ts
packages/@secretlint/secretlint-rule-openai/test/snapshots/ng.secret/input.txt
packages/@secretlint/secretlint-rule-openai/test/snapshots/ng.secret/output.json
packages/@secretlint/secretlint-rule-openai/test/snapshots/ok.valid/input.txt
packages/@secretlint/secretlint-rule-openai/test/snapshots/ok.valid/output.json
packages/@secretlint/secretlint-rule-openai/tsconfig.json

Closes #676 
Based on `yarn gen:rule`.

feat: Add @secretlint/secretlint-rule-openai package for detecting OpenAI API tokens

---

packages/@secretlint/secretlint-rule-preset-recommend/package.json
packages/@secretlint/secretlint-rule-preset-recommend/src/index.ts
packages/@secretlint/secretlint-rule-preset-recommend/test/index.test.ts
packages/@secretlint/secretlint-rule-preset-recommend/test/snapshots/secretlint-rule-openai/ng.secret/input.txt
packages/@secretlint/secretlint-rule-preset-recommend/test/snapshots/secretlint-rule-openai/ng.secret/output.json
packages/@secretlint/secretlint-rule-preset-recommend/test/snapshots/secretlint-rule-openai/ok.valid/input.txt
packages/@secretlint/secretlint-rule-preset-recommend/test/snapshots/secretlint-rule-openai/ok.valid/output.json

`@secretlint/secretlint-rule-preset-recommend` include [OpenAI](https://openai.com/) API key detection from Now!
resolve #680

feat(recommend): Add OpenAI rule to recommend

---

README.md

docs: Add OpenAI

---

.github/workflows/test-diff.yml
.secretlintrc.json
README.md

CI: add test-diff actions

---

.github/workflows/publish-artifact.yml

`secretlint_0.0.1_linux_amd64`

CI: use lowercase for binary

---

.github/workflows/test.yml

In sometimes, turbo run is hang.

CI: add -vvv to turbo run

---

.github/workflows/publish-artifact.yml

CI: fix publish

---

packages/@secretlint/formatter/package.json
publish/binary-compiler/src/entry.ts
yarn.lock

It will improve binary-compiler
- https://github.com/textlint/textlint/pull/1426

fix(deps): update to @textlint/linter-formatter@14.2.1

---

packages/@secretlint/secretlint-rule-aws/README.md
packages/@secretlint/secretlint-rule-aws/src/index.ts
packages/@secretlint/secretlint-rule-aws/test/snapshots/ok.AWS Access Key ID--enableIDScanRule-false/.secretlintrc.json
packages/@secretlint/secretlint-rule-aws/test/snapshots/ok.AWS Access Key ID--enableIDScanRule-false/input
packages/@secretlint/secretlint-rule-aws/test/snapshots/ok.AWS Access Key ID--enableIDScanRule-false/output.json
packages/@secretlint/secretlint-rule-preset-canary/src/index.ts

`Default: true` - it preserve current behavior.
We will change it to `false` by default.
ref #855

feat(aws): add `enableIDScanRule` option

---

.github/workflows/benchmark.yml
.github/workflows/codeql-analysis.yml
.github/workflows/comment-publish-artifact.yml
.github/workflows/create-release-pr.yml
.github/workflows/publish-artifact.yml
.github/workflows/publish.yml
.github/workflows/test-diff.yml
.github/workflows/test.yml

Pin all actions's version.
```
pinact run
pinact run -u
```
https://github.com/suzuki-shunsuke/pinact?tab=readme-ov-file

CI: pin version

---

packages/secretlint/test/cli.test.ts
packages/secretlint/test/snapshots/--version/options.ts
packages/secretlint/test/snapshots/--version/output.json

fix failed test for `--version`

test(secretlint): fix --version test

---

packages/@secretlint/config-loader/package.json
packages/@secretlint/formatter/package.json
packages/@secretlint/secretlint-rule-github/src/index.ts
yarn.lock

chore(deps): remove try-resolve

---

package.json
yarn.lock

update lint-staged from v13 to v16
https://github.com/lint-staged/lint-staged/blob/main/CHANGELOG.md

chore: update lint-staged from v13 to v16

---

packages/@secretlint/config-loader/src/package-name-util.ts
packages/@secretlint/secretlint-rule-aws/src/index.ts
packages/@secretlint/secretlint-rule-azure/src/index.ts

refactor for loop syntax & import multiple times

refactor: refactor for loop syntax & import multiple times

---

packages/@secretlint/source-creator/package.json
packages/@secretlint/source-creator/src/index.ts
yarn.lock

update istextorbinary from v6 to v9
<https://github.com/bevry/istextorbinary/blob/master/HISTORY.md>

chore: update istextorbinary from v6 to v9

---

README.md
docs/configuration.md
packages/@secretlint/formatter/README.md
packages/@secretlint/formatter/src/index.ts
packages/@secretlint/secretlint-rule-aws/README.md
packages/secretlint/test/create-secretlintrc.test.ts

chore: fix typos

---

packages/@secretlint/secretlint-rule-preset-canary/test/snapshots/secretlint-rule-gcp/ng.privatekey-json/output.json
packages/@secretlint/secretlint-rule-preset-recommend/test/snapshots/secretlint-rule-gcp/ng.privatekey-json/output.json
packages/@secretlint/secretlint-rule-privatekey/src/index.ts

```Copilot Generated Description:``` Update the regex pattern to ensure that the beginning private key matches the corresponding ending private key.
related https://github.com/secretlint/secretlint/issues/1048

Private key rule should enforce correct end private key footer

---

packages/secretlint/package.json
yarn.lock

update read-pkg from v8 to v9
- <https://github.com/sindresorhus/read-pkg/releases>

chore: update read-pkg from v8 to v9

---

packages/@secretlint/config-loader/test/index.test.ts
packages/@secretlint/formatter/test/index.test.ts
packages/@secretlint/types/src/SecretLintRule.ts
packages/@secretlint/types/vitest.config.ts

fix(types): fix type tests

---

.github/workflows/benchmark.yml
.github/workflows/codeql-analysis.yml
.github/workflows/comment-publish-artifact.yml
.github/workflows/create-release-pr.yml
.github/workflows/publish-artifact.yml
.github/workflows/publish.yml
.github/workflows/test-diff.yml
.github/workflows/test.yml

apply zizmor lint
https://docs.zizmor.sh/

CI: fix GitHub Workflows

---

.github/workflows/release.yml

Ensure npm 11.5.1 or later is installed for OICD.

CI: add npm install -g npm

---

.github/workflows/release.yml

CI: fix workflow condition
