examples/benchmark/profile.js, packages/@secretlint/config-validator/package.json, packages/@secretlint/core/package.json, packages/@secretlint/core/src/RunningEvents.ts, packages/@secretlint/core/src/index.ts, packages/@secretlint/node/src/index.ts, packages/@secretlint/profiler/LICENSE, packages/@secretlint/profiler/README.md, packages/@secretlint/profiler/package.json, packages/@secretlint/profiler/src/browser.ts, packages/@secretlint/profiler/src/index.ts, packages/@secretlint/profiler/src/node.ts, packages/@secretlint/profiler/test/mocha.opts, packages/@secretlint/profiler/test/tsconfig.json, packages/@secretlint/profiler/tsconfig.json, packages/secretlint/package.json, packages/secretlint/src/cli.ts, yarn.lock
```
$ secretlint --profile "**/*"
@node>load-config - 73.62ms
@core>setup-rule||@secretlint/secretlint-rule-preset-recommend - 0.5ms
@core>setup-rules - 0.59ms
@core>rule-handler||@secretlint/secretlint-rule-aws - 1.43ms
@core>rule-handler||@secretlint/secretlint-rule-privatekey - 0.32ms
@core>rule-handler||@secretlint/secretlint-rule-npm - 0.17ms
@core>lint||<cwd>/targets/textlint.github.io/sitemap.xml - 2.79ms
@core>setup-rule||@secretlint/secretlint-rule-preset-recommend - 0.07ms
@core>setup-rules - 0.1ms
@core>rule-handler||@secretlint/secretlint-rule-aws - 0.21ms
@core>rule-handler||@secretlint/secretlint-rule-privatekey - 0.1ms
@core>rule-handler||@secretlint/secretlint-rule-npm - 0.07ms
@core>lint||<cwd>/targets/textlint.github.io/help.html - 0.45ms …
```
=> feat(profiler): add --profiler flag

.changeset/config.json, .changeset/tough-actors-allow.md, packages/@secretlint/quick-start/package.json
```
npx @secretlint/quick-start "**/*"
```
Refer to `@secretlint/quick-start`'s `quick-start` script by default.
=> fix(quick-start): fix bin script name

packages/@secretlint/config-loader/src/index.ts, packages/@secretlint/node/src/index.ts, packages/@secretlint/profiler/src/index.ts, packages/secretlint/src/cli.ts
It allow to pass JSON string instead of secretlintrc file path.
This feature is useful for in-memory linting like history scanner https://github.com/secretlint/secretlint/issues/34
```
git filter-branch --tree-filter 'secretlint --secretlintrcJSON "$(cat .secretlintrc.json)" "**/*" --debug"' --all
```
=> feat(cli): support --secretlintrcJSON flag

packages/@secretlint/secretlint-rule-example/README.md
=> docs(rule-example): fix typo

README.md, packages/@secretlint/secretlint-rule-preset-canary/package.json, packages/@secretlint/secretlint-rule-preset-canary/src/index.ts, packages/@secretlint/secretlint-rule-secp256k1-privatekey/README.md, packages/@secretlint/secretlint-rule-secp256k1-privatekey/src/index.ts
This PR will fix benchmark scripts
#107 
Via `.secretlintrc.json`
```json
{
"rules": [
{
"id": "@secretlint/secretlint-rule-preset-recommend"
},
{
"id": "@secretlint/secretlint-rule-secp256k1-privatekey"
}
]
}
```
=> revert: remove secretlint-rule-secp256k1-privatekey from canary

CHANGELOG.md, lerna.json, packages/@secretlint/secretlint-rule-secp256k1-privatekey/CHANGELOG.md, packages/@secretlint/secretlint-rule-secp256k1-privatekey/package.json
**secretlint-rule-secp256k1-privatekey:** handle thrown exception due to invalid key ([#110](https://github.com/secretlint/secretlint/issues/110)) ([320b344](https://github.com/secretlint/secretlint/commit/320b3446d7afd85e342cb9bb15f6e9df7dae8036))
A check is missed. `secp256k1.privateKeyVerify()` can throw for invalid keys as well.
=> v1.0.2: secretlint-rule-secp256k1-privatekey bug fix

packages/@secretlint/secretlint-rule-no-k8s-kind-secret/LICENSE, packages/@secretlint/secretlint-rule-no-k8s-kind-secret/README.md, packages/@secretlint/secretlint-rule-no-k8s-kind-secret/package.json, packages/@secretlint/secretlint-rule-no-k8s-kind-secret/src/index.ts, packages/@secretlint/secretlint-rule-no-k8s-kind-secret/test/index.test.ts, packages/@secretlint/secretlint-rule-no-k8s-kind-secret/test/mocha.opts, packages/@secretlint/secretlint-rule-no-k8s-kind-secret/test/snapshots/ng.kind-secret-multiple/input.yml, packages/@secretlint/secretlint-rule-no-k8s-kind-secret/test/snapshots/ng.kind-secret-multiple/output.json, packages/@secretlint/secretlint-rule-no-k8s-kind-secret/test/snapshots/ng.kind-secret/input.yml, packages/@secretlint/secretlint-rule-no-k8s-kind-secret/test/snapshots/ng.kind-secret/output.json, packages/@secretlint/secretlint-rule-no-k8s-kind-secret/test/snapshots/ok.valid/input.txt, packages/@secretlint/secretlint-rule-no-k8s-kind-secret/test/snapshots/ok.valid/input.yaml, packages/@secretlint/secretlint-rule-no-k8s-kind-secret/test/snapshots/ok.valid/output.json, packages/@secretlint/secretlint-rule-no-k8s-kind-secret/test/tsconfig.json, packages/@secretlint/secretlint-rule-no-k8s-kind-secret/tsconfig.json, yarn.lock
Implemented `secretlint-rule-no-k8s-kind-secret` rule that disallow to use `Kind: Secret` manifest in a repository.
fix #112
=> feat(secretlint-rule-no-k8s-kind-secret): add new rule

packages/@secretlint/core/src/helper/SecretLintRuleMessageTranslator.ts, packages/@secretlint/core/test/helper/SecretLintRuleMessageTranslator.test.ts
secretlint throw an error `Error: Placeholder:{{XXX}} still existed.` when reporting message includes `{{XXXX}}` after formatted.
This assertion logic is wrong. This PR fix assertion.
fix #116
=> fix(core): fix placeholder assertion for rule

packages/@secretlint/messages-to-markdown/src/index.ts, packages/@secretlint/secretlint-rule-no-homedir/.mocharc.json, packages/@secretlint/secretlint-rule-no-homedir/LICENSE, packages/@secretlint/secretlint-rule-no-homedir/README.md, packages/@secretlint/secretlint-rule-no-homedir/package.json, packages/@secretlint/secretlint-rule-no-homedir/src/index.ts, packages/@secretlint/secretlint-rule-no-homedir/test/index.test.ts, packages/@secretlint/secretlint-rule-no-homedir/test/snapshots/ng.homedir/.secretlintrc.json, packages/@secretlint/secretlint-rule-no-homedir/test/snapshots/ng.homedir/input.txt, packages/@secretlint/secretlint-rule-no-homedir/test/snapshots/ng.homedir/output.json, packages/@secretlint/secretlint-rule-no-homedir/test/snapshots/ng.patial-homedir/.secretlintrc.json, packages/@secretlint/secretlint-rule-no-homedir/test/snapshots/ng.patial-homedir/input.txt, packages/@secretlint/secretlint-rule-no-homedir/test/snapshots/ng.patial-homedir/output.json, packages/@secretlint/secretlint-rule-no-homedir/test/snapshots/ok.valid/.secretlintrc.json, packages/@secretlint/secretlint-rule-no-homedir/test/snapshots/ok.valid/input.txt, packages/@secretlint/secretlint-rule-no-homedir/test/snapshots/ok.valid/output.json, packages/@secretlint/secretlint-rule-no-homedir/test/tsconfig.json, packages/@secretlint/secretlint-rule-no-homedir/tsconfig.json, yarn.lock
Implement `secretlint-rule-no-homedir` that disallow to include user homedir in each files.
It will prevent to unexpected expose user's path and user name.
fix #62
=> feat(secretlint-rule-no-homedir): add new rule

package.json, packages/secretlint/src/search.ts, packages/secretlint/test/snapshots/non-ascii-file/input-non-ascii-file-日本語.md, packages/secretlint/test/snapshots/non-ascii-file/options.ts, packages/secretlint/test/snapshots/non-ascii-file/output.json
I've noticed that secretlint can not handle non-ascii file name like `non-asciii-日本語ファイル.md`.
It will throw an error if you check a non-ascii file with secretlint.
> Error: ENAMETOOLONG: name too long,
This problem is caused by globby/fast-glob result, I think.
- ascii file: absolute path
- non-ascii file: file name only(not relative path)
I've add `absolute` option explicitly as workaround.
=> fix(secretlint): fix handling for non-ascii file path

packages/@secretlint/secretlint-rule-npm/README.md, packages/@secretlint/secretlint-rule-npm/src/index.ts, packages/@secretlint/secretlint-rule-npm/test/snapshots/NPM_ACCESS_TOKEN/input.txt, packages/@secretlint/secretlint-rule-npm/test/snapshots/NPM_ACCESS_TOKEN/output.json
Support to detect npm access token like `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`.
fix #200
=> feat(npm): support `npm_` prefix access token

.github/workflows/publish-artifact.yml
fix #252.
- Build and push a docker images for linux/amd64 and linux/arm64 using docker buildx.
- https://github.com/docker/setup-buildx-action
- https://github.com/docker/setup-qemu-action
- Change the image push destination from docker.pkg.github.com to ghcr.io. Because docker.pkg.github.com does not support multi-platform images.
- > The Docker service docker.pkg.github.com has not (and will not) receive this update. The new Container Registry (GHCR) now supports multi-arch images.
https://github.community/t/publish-docker-package-fails/17569/10
- I have tried publishing in my repository.
- pull request: https://github.com/korosuke613/secretlint/pull/4
- publish logs: https://github.com/korosuke613/secretlint/runs/5815978333
- ghcr.io: …
=> feat(docker): support arm64 for image

publish/docker/Dockerfile
I noticed that formatt is not align to core version.
=> fix(docker): use latest formatter version

.github/ISSUE_TEMPLATE/bug-report.md
Since `secrelint` only supports longs option, `-v` causes an error.
```
Error: Not found target files
5.2.1
```
=> chore(issue-template): Fix issue template: how to check the secretlint's version

packages/@secretlint/config-creator/package.json, packages/@secretlint/config-creator/test/fixtures/package.json, packages/@secretlint/config-creator/test/index.test.ts, packages/secretlint/test/create-secretlintrc.test.ts, packages/secretlint/test/fixtures/package.json
Add tests as bellow:
- Check to create `.secretlintrc.json` when `runConfigCreator` is called
- Check whether `createConfig` works well
Ref. #33
=> test(runConfigCreator): add tests for secretlint --init

packages/@secretlint/secretlint-rule-filter-comments/src/parse-comment.ts, packages/@secretlint/secretlint-rule-filter-comments/test/parseComment.test.ts, packages/@secretlint/secretlint-rule-filter-comments/test/snapshots/ok.ignore-in-markdown/input.md, packages/@secretlint/secretlint-rule-filter-comments/test/snapshots/ok.ignore-in-markdown/output.json
Markdown comment `` does not work correctly.
fix #371
=> fix(filter-comment): fix secretlint-disable comment parsing

packages/@secretlint/secretlint-rule-preset-canary/package.json, packages/@secretlint/secretlint-rule-preset-canary/rollup.config.mjs, yarn.lock
Follow up
- #405 
It will fix following error:
> Uncaught ReferenceError: process is not defined
=> fix(canary): remove `process.platform` from browser bundle

renovate.json
renovate always failed because it will push to main brach.
it is blocked by protect branches.
It will be resolved by using `"automergeType": "pr"`
=> fix(renovate): use "automergeType": "pr"

packages/@secretlint/quick-start/bin/quick-start.js
- #399 
`@secretlint/quick-start` should align with `secretlint` command
=> fix(quick start): exit status align to secretlint command

packages/@secretlint/config-creator/test/index.test.ts, packages/@secretlint/config-loader/test/index.test.ts, packages/@secretlint/config-loader/test/snapshot.test.ts, packages/@secretlint/formatter/src/index.ts, packages/@secretlint/formatter/test/index.test.ts, packages/@secretlint/formatter/test/snapshots/input.ts, packages/@secretlint/node/test/index.test.ts, packages/@secretlint/quick-start/src/index.ts, packages/@secretlint/secretlint-formatter-sarif/test/index.test.ts, packages/@secretlint/secretlint-formatter-sarif/test/snapshots/input.ts, packages/@secretlint/secretlint-rule-preset-recommend/import-tests.js, packages/@secretlint/secretlint-rule-preset-recommend/test/index.test.ts, packages/@secretlint/source-creator/test/index.test.ts
Fix the __dirname mimic to remove a leading slash in it by using fileURLToPath instead.
Closes #562.
Ref: https://humanwhocodes.com/snippets/2023/01/mimicking-dirname-filename-nodejs-esm/
I checked through the repo and replaced all `__dirname`.
=> fix: use fileURLToPath for mimicked __dirname

.github/workflows/test.yml
=> CI: fix tests on Windows

packages/secretlint/src/search.ts
Fixes #589
The usage of `path.posix` causes the error because it does not handle the drive name in Windows correctly, so stop using it.
However, `globby` or `fast-glob`, its dependent, only supports forward-slash so replace double back slashes with it.
https://github.com/mrmlnc/fast-glob#pattern-syntax
=> fix: stop using path.posix

.gitattributes, examples/cli/package.json, examples/quick-start/package.json, packages/@secretlint/config-loader/.mocharc.json, packages/@secretlint/config-loader/test/snapshot.test.ts, packages/@secretlint/formatter/.mocharc.json, packages/@secretlint/formatter/src/index.ts, packages/@secretlint/formatter/test/index.test.ts, packages/@secretlint/node/.mocharc.json, packages/@secretlint/node/test/index.test.ts, packages/@secretlint/quick-start/package.json, packages/@secretlint/secretlint-formatter-sarif/test/index.test.ts, packages/@secretlint/source-creator/test/index.test.ts, packages/@secretlint/tester/src/index.ts, packages/secretlint/src/cli.ts, packages/secretlint/src/create-secretlintrc.ts, packages/secretlint/src/search.ts, packages/secretlint/test/cli.test.ts, packages/secretlint/test/create-secretlintrc.test.ts, yarn.lock
Fix various bugs on Windows
- fix `secretlint --debug`
- fix to load custom formatter on Windows
- `@secretlint/tester` normalize file path by default
- Previously, it has difference between Windows and Linux
- `secretlint [windows path]` supports
refs #590
=> fix: fix behaviour on Windows.

packages/@secretlint/secretlint-rule-aws/package.json, packages/@secretlint/secretlint-rule-aws/src/index.ts, packages/@secretlint/secretlint-rule-azure/package.json, packages/@secretlint/secretlint-rule-azure/src/index.ts, yarn.lock
=> refactor: use `` new RegExp(String.raw`...`) `` instead of regx

packages/@secretlint/secretlint-rule-shopify/src/index.ts
Corrected the name of the constant used for matching Shopify keys. Changed from `SENDGRID_KEY_PATTERN` to `SHOPIFY_KEY_PATTERN` to accurately reflect its purpose.
=> fix: typo in Shopify key pattern constant

packages/@secretlint/secretlint-rule-secp256k1-privatekey/package.json, yarn.lock
Ref https://github.com/cryptocoinjs/secp256k1-node/releases/tag/v5.0.0
=> fix(deps): update to secp256k1@5.0.0

README.md
GitHub Code Scanning supports [Push protection for users - GitHub Docs](https://docs.github.com/en/code-security/secret-scanning/push-protection-for-users).
=> docs: add Push protection of GitHub Code Scanning

packages/@secretlint/secretlint-rule-sendgrid/src/index.ts, packages/@secretlint/secretlint-rule-sendgrid/test/snapshots/ng.apikey/input.txt, packages/@secretlint/secretlint-rule-sendgrid/test/snapshots/ng.apikey/output.json
The latest sendgrid API key contained underscores instead of hyphens, or a pattern with neither, so we added them.
=> fix(sendgrid): fix SENDGRID_KEY_PATTERN

packages/secretlint/package.json, yarn.lock
Update to globby@14.0.1 which fix read permission error on ignore files search
refs https://github.com/sindresorhus/globby/releases/tag/v14.0.1
refs https://github.com/sindresorhus/globby/pull/259
closes https://github.com/secretlint/secretlint/issues/460
=> fix(secretlint): fix "ENOENT: no such file or directory"

.github/workflows/publish-artifact.yml, package.json, yarn.lock
> The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings.
It seems that it cannot be used in the free plan.
=> CI: remove macos-latest-xlarge

packages/@secretlint/messages-to-markdown/src/cli.ts, packages/@secretlint/resolver/src/index.ts, packages/@secretlint/resolver/test/index.test.ts, packages/secretlint/src/cli.ts
resolve: https://github.com/secretlint/secretlint/issues/1005
dir is 
- **oss**
- ts
- **secretlint**
- packages
- secretlint
- bin
- **secretlint.js**
=> hotfix: secretlint --version returning 1.0.0

packages/@secretlint/secretlint-rule-github/src/index.ts
Fixes `Error: Unknown type:undefined` for GitHub user-to-server tokens (ghu) and updates the decription of `ghs` to `GitHub server-to-server tokens`
Fixes [Error: Unknown type:undefined for GitHub user-to-server tokens (ghu)](https://github.com/secretlint/secretlint/issues/1036)
=> Add missing `ghu` to typeMap and fix description

.github/ISSUE_TEMPLATE/question.md, docs/configuration.md, docs/secretlint-rule.md
correct typos in documentation files
=> fix: correct typos in documentation files
